feat: checks createAt
defi-wonderland/prophet-core pull request #37
Opened 2024-07-26 16:13 UTC by ashitakah

# 🤖 Linear

Closes GRT-18

2024-07-26 16:29 UTC, 0xShaito submitted a review, later dismissed

2024-07-26 22:05 UTC, 0xJabberwock requested changes
The existential validation of requests seems good to me. However, you should check as well whether the response exists in all related functions but `proposeResponse()`; similarly, the existence of the dispute should be validated in all but `disputeResponse()`.

2024-07-26 22:05 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
>      bytes32 _responseId = keccak256(abi.encode(_response));
Within `_validateDispute()`, the response should be existent as well.

2024-07-31 01:43 UTC, ashitakah commented on solidity/contracts/Oracle.sol
>      bytes32 _responseId = keccak256(abi.encode(_response));
👍

2024-07-31 02:46 UTC, 0xJabberwock requested changes

2024-07-31 02:46 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +    _responseId = _validateProposeResponse(_request, _response);
Being called just once, I'd say `_validateProposeResponse()` isn't worth it.

2024-07-31 02:46 UTC, 0xJabberwock commented on solidity/test/unit/Oracle.t.sol
> +    oracle.mock_setResponseCreatedAt(_getId(mockResponse), uint128(block.number));
The second line shouldn't be there.

2024-07-31 02:46 UTC, 0xJabberwock commented on solidity/test/unit/Oracle.t.sol
> +    oracle.mock_setDisputeCreatedAt(_disputeId, uint128(block.number));
You shouldn't mock `disputeCreatedAt` in `disputeResponse()`, since it is the function in which it gets created.

2024-07-31 02:46 UTC, 0xJabberwock commented on solidity/test/unit/Oracle.t.sol
> +    vm.expectRevert(IOracle.Oracle_InvalidRequestBody.selector);
`Oracle_InvalidDisputeBody`, and not `Oracle_InvalidRequestBody`, is what `test_disputeResponse_revertIfProposerIsNotValid` should expect.

2024-07-31 02:46 UTC, 0xJabberwock commented on solidity/test/unit/Oracle.t.sol
> +    vm.expectRevert(IOracle.Oracle_InvalidRequestBody.selector);
Here, `test_disputeResponse_revertIfInvalidRequest` is redundant and can be deleted.

2024-07-31 02:46 UTC, 0xJabberwock commented on solidity/test/unit/Oracle.t.sol
> +  function test_updateDisputeStatus_revertsIfInvalidResponse() public {
`test_updateDisputeStatus_revertsIfInvalidDispute` is missing.

2024-08-01 14:52 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +    _responseId = _validateProposeResponse(_request, _response);
I think we should leave it as I will also add an external view method for this so that modules can call this validation

2024-08-01 14:52 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +    _responseId = _validateProposeResponse(_request, _response);
I think we should leave it as I will also add an external view method for this so that modules can call this validation

2024-08-03 01:08 UTC, 0xShaito requested changes

2024-08-03 01:08 UTC, 0xShaito commented on solidity/contracts/Validator.sol
> -    if (ORACLE.responseCreatedAt(_responseId) == 0) revert Validator_InvalidResponse();
The validator is being used in a couple other contracts in the prophet-modules. We can't just remove this validation.

Maybe move the core logic (validate ids) to a library and use the library in the Oracle and in the validator?

2024-08-05 06:22 UTC, 0xJabberwock requested changes

2024-08-05 06:22 UTC, 0xJabberwock commented on solidity/test/unit/Oracle.t.sol
> -  function test_proposeResponse_revertsIfInvalidRequest() public {
This test case should be kept.

2024-08-06 03:12 UTC, ashitakah commented on solidity/test/unit/Oracle.t.sol
> +    oracle.mock_setResponseCreatedAt(_getId(mockResponse), uint128(block.number));
👍

2024-08-06 03:17 UTC, ashitakah commented on solidity/test/unit/Oracle.t.sol
> +    oracle.mock_setDisputeCreatedAt(_disputeId, uint128(block.number));
👍

2024-08-06 03:17 UTC, ashitakah commented on solidity/test/unit/Oracle.t.sol
> +  function test_updateDisputeStatus_revertsIfInvalidResponse() public {
👍

2024-08-06 04:04 UTC, ashitakah commented on solidity/scripts/Deploy.sol
> +  Validator validator;
👍

2024-08-06 04:04 UTC, ashitakah commented on solidity/contracts/Validator.sol
> -    if (ORACLE.responseCreatedAt(_responseId) == 0) revert Validator_InvalidResponse();
👍

2024-08-06 12:31 UTC, 0xShaito requested changes

2024-08-06 12:31 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +    _responseId = ValidatorLib._validateResponse(_request, _response);
Validate that the request exists requestCreatedAt

2024-08-06 17:10 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    _responseId = ValidatorLib._validateResponse(_request, _response);
👍

2024-08-06 17:21 UTC, 0xJabberwock requested changes

2024-08-06 17:21 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
>        revert Oracle_InvalidResponseBody();
Where appropriate within `Oracle`, I suggest renaming the inexistence errors to `Oracle_Invalid{Request/Response/Dispute}`.

2024-08-06 17:21 UTC, 0xJabberwock commented on solidity/test/unit/Validator.t.sol
> -    assertEq(disputeId, keccak256(abi.encode(mockDispute)));
All the test cases of the above kind should be kept within `Validator.t.sol`, as we're still returning IDs in the validation functions.

Actually, it would make sense to duplicate all the test cases moved to `ValidatorLib.t.sol` in order to make sure that the library is properly being called.

2024-08-06 17:21 UTC, 0xJabberwock commented on solidity/test/unit/Validator.t.sol
> -  function test_getId_request() public {
The deletion of all these also has to do with the previous comment.

2024-08-06 17:30 UTC, ashitakah commented on solidity/contracts/Oracle.sol
>        revert Oracle_InvalidResponseBody();
👍

2024-08-06 17:31 UTC, ashitakah commented on solidity/test/unit/Validator.t.sol
> -    assertEq(disputeId, keccak256(abi.encode(mockDispute)));
I did it for not duplicate test logic in the contracts, even so, i can do it again all those tests.

2024-08-06 17:31 UTC, ashitakah commented on solidity/test/unit/Validator.t.sol
> -  function test_getId_request() public {
👍

2024-08-06 18:00 UTC, 0xJabberwock requested changes

2024-08-06 18:00 UTC, 0xJabberwock commented on solidity/test/mocks/contracts/MockRequestModule.sol
Beware! This mock contract has been erased.

2024-08-06 18:00 UTC, 0xJabberwock commented on solidity/contracts/Validator.sol
> +  function _validateRequestAndResponse(
I don't support the addition of `_validateRequestAndResponse()`, both in `Validator` and `ValidatorLib`. It works the same as `_validateResponse` in each except that it also returns the `_requestId`.

2024-08-06 18:00 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +      revert Oracle_InvalidRequestBody();
Only the addition of lines 111 and 112 would have been enough for the matter of checking the existence of a request.

2024-08-06 18:22 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +      revert Oracle_InvalidRequestBody();
I think it's just because it gives you the _requestId

2024-08-06 18:46 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +      revert Oracle_InvalidRequestBody();
I needed a function that gives me the _requestId to check it in the createdAt

2024-08-06 19:02 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +      revert Oracle_InvalidRequestBody();
👍

2024-08-06 19:02 UTC, ashitakah commented on solidity/contracts/Validator.sol
> +  function _validateRequestAndResponse(
👍

2024-08-06 19:05 UTC, 0xJabberwock approved these changes
🔥

2024-08-06 19:07 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +      revert Oracle_InvalidRequestBody();
> I needed a function that gives me the _requestId to check it in the createdAt

I think you could just reuse the functionality from `_getId()` in order to avoid creating `_validateRequestAndResponse()`, which by the way doesn't validate the request in any sense.

2024-08-06 19:28 UTC, 0xShaito approved these changes

2024-08-06 19:28 UTC, merged