feat: validator
defi-wonderland/prophet-core pull request #39
Opened 2024-08-01 15:28 UTC by 0xShaito

# 🤖 Linear

Closes OPO-XXX

2024-08-01 18:53 UTC, 0xJabberwock requested changes

2024-08-01 18:53 UTC, 0xJabberwock commented on solidity/test/unit/Validator.t.sol
> +    vm.expectRevert(IValidator.Validator_InvalidDispute.selector);
Should be `test_validateResponseAndDispute_InvalidDispute`.

2024-08-01 18:53 UTC, 0xJabberwock commented on solidity/contracts/Validator.sol
> +    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert Validator_InvalidDispute();
Shouldn't you check for the existence of the `_responseId` here as well?

2024-08-01 18:53 UTC, 0xJabberwock commented on solidity/contracts/Validator.sol
> +   * @notice Validates the correctness of a request-response pair
Besides validating correctness, these functions also validate existence now.

2024-08-01 18:53 UTC, 0xJabberwock commented on solidity/contracts/Validator.sol
> +  function _validateResponse(
`_validateRequest()`, for checking that a request exists, is missing.

Also, it should be thought whether adding `_validateRequestAndResponse`, `_validateRequestAndDispute` or `_validateRequestResponseAndDispute` is worth it.

2024-08-01 18:53 UTC, 0xJabberwock commented on solidity/contracts/Module.sol
>    function validateParameters(bytes calldata _encodedParameters) external view virtual returns (bool _valid) {}
Wouldn't this be expected to be within `Validator`?

2024-08-01 18:53 UTC, 0xJabberwock commented on solidity/test/unit/Validator.t.sol
Check linter warnings in this file.

2024-08-01 19:07 UTC, 0xShaito commented on solidity/contracts/Module.sol
>    function validateParameters(bytes calldata _encodedParameters) external view virtual returns (bool _valid) {}
No. This is specific to the parameters for the module itself

2024-08-01 19:09 UTC, 0xShaito commented on solidity/contracts/Validator.sol
> +    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert Validator_InvalidDispute();
No! In the start I did but for a dispute to be created there is already a validation that the response exists.

If a dispute exists, the response validation has already been aplied for it to be created in the first place

2024-08-01 19:13 UTC, 0xShaito commented on solidity/contracts/Validator.sol
> +  function _validateResponse(
Because validation of request is only calling oracle.requestCreationTime I think that it was kinda unnecesary tbh

2024-08-01 19:26 UTC, ashitakah submitted a review, later dismissed

2024-08-01 19:36 UTC, 0xJabberwock commented on solidity/contracts/Validator.sol
> +    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert Validator_InvalidDispute();
> for a dispute to be created there is already a validation that the response exists

There is no such validation yet.

2024-08-01 19:42 UTC, ashitakah requested changes

2024-08-01 19:42 UTC, ashitakah commented on solidity/test/unit/Validator.t.sol
> +    bytes32 disputeId = validator.getId(mockDispute);
also here linter problem

2024-08-02 01:43 UTC, 0xJabberwock approved these changes

2024-08-02 12:21 UTC, merged