feat: access control
defi-wonderland/prophet-core pull request #52
Opened 2024-10-17 18:25 UTC by ashitakah

2024-10-17 18:41 UTC, xorsal commented on solidity/contracts/utils/OracleTypehash.sol
> +bytes32 constant _FINALIZE_TYPEHASH = keccak256('Finalize(Request _request, Response _response)');
I think EIP-712 typehashes shouldn't have spaces after each comma.

2024-10-17 18:44 UTC, xorsal commented on solidity/contracts/utils/OracleTypehash.sol
> +bytes32 constant _FINALIZE_TYPEHASH = keccak256('Finalize(Request _request, Response _response)');
`bytes32 constant MAIL_TYPEHASH = keccak256("Mail(address from,address to,string contents)");`

https://eips.ethereum.org/EIPS/eip-712

2024-10-18 15:10 UTC, xorsal commented on solidity/contracts/Oracle.sol
> +      revert Oracle_NotDisputeOrResolutionModule(_accessControl.user);
If this function isn't callable by users it shouldn't use `AccessControl`.

2024-10-22 06:06 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +  function createRequests(
These need access control too

2024-10-22 06:08 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +    allowedModule[_requestId][_request.accessControlModule] = true;
I don't think the access control module calls any function so maybe we should give it allowedModule permissions?

2024-10-24 01:58 UTC, ashitakah commented on solidity/contracts/utils/OracleTypehash.sol
> +bytes32 constant _FINALIZE_TYPEHASH = keccak256('Finalize(Request _request, Response _response)');
👍

2024-10-24 02:01 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +  function createRequests(
why? This should be free, as we set the access control in the request

2024-10-24 04:51 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    allowedModule[_requestId][_request.accessControlModule] = true;
👍

2024-10-24 04:52 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +      revert Oracle_NotDisputeOrResolutionModule(_accessControl.user);
👍

2024-10-24 05:58 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +  function createRequests(
RequestModule may bond tokens for the request to pay the proposer. And it does in existing modules.

2024-10-24 06:54 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
>    function proposeResponse(
Not validating if the access control is approved. I would add a second modifier to each of the functions

2024-10-24 07:02 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
>    function proposeResponse(
This is for all the fns that have access control

2024-10-24 07:02 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +  mapping(address _user => mapping(address _accessControlModule => bool _approved)) public isAccessControlApproved;
No function to approve an access control module

2024-10-24 07:06 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +    hasAccess(_request.accessControlModule, _RESOLVE_TYPEHASH, abi.encode(_request, _response, _dispute), _accessControl)
Do we actually need access control if we never use msg.sender?

2024-10-24 07:06 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
>    function updateDisputeStatus(
This fn seems to only be callable by modules. Not by users. I don't think we need access control for it

2024-10-24 07:08 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +  function finalize(
Why do we need the msg.senders in finalize? Is there a use for it? If not sure, can you ask in the prophet channel what the intended use is?

2024-10-24 07:10 UTC, 0xShaito commented on solidity/contracts/Oracle.sol
> +    hasAccess(_request.accessControlModule, _CREATE_TYPEHASH, abi.encode(_request), _accessControl)
Lets change this so that we validate access in the external function.

In the createRequest you would need to loop the hasAccess function taking much more gas than needed

2024-10-24 07:13 UTC, 0xShaito commented on solidity/test/integration/EscalateDispute.t.sol
>    function test_escalateDispute() public {
Create a mock access control module to test access control module functionality in a separate test

2024-10-24 07:13 UTC, 0xShaito commented on solidity/test/integration/EscalateDispute.t.sol
>    function test_escalateDispute() public {
This for all the functions

2024-10-24 07:16 UTC, 0xShaito commented on solidity/test/integration/IntegrationBase.sol
> +    address[] memory _allowedCallers = new address[](1);
This is part of the test but I don't like it this way as we are testing everything with access control.

For the existing tests, use accessControlModule = address(0) and make the users call themselves (no access control module). And then for each of the cases I would prefer adding a separate test that tests access control exclusively on each of the function like this. Also we need cases were access is rejected too

2024-10-24 07:18 UTC, 0xShaito commented on solidity/test/mocks/contracts/MockAtomicArbitrator.sol
> +    // oracle.resolveDispute(_request, _response, _dispute);
What hapened here?

2024-10-24 07:19 UTC, 0xShaito requested changes
Great PR! I think some more testing is missing though. AccessController is also not tested in all of its cases individually. Close to ready!

2024-10-24 16:16 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    hasAccess(_request.accessControlModule, _RESOLVE_TYPEHASH, abi.encode(_request, _response, _dispute), _accessControl)
👍

2024-10-24 16:18 UTC, ashitakah commented on solidity/contracts/Oracle.sol
>    function updateDisputeStatus(
👍

2024-10-24 16:21 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +  function finalize(
commented in the discord channel

2024-10-24 16:24 UTC, ashitakah commented on solidity/test/integration/IntegrationBase.sol
> +    address[] memory _allowedCallers = new address[](1);
For me makes a lot of sense having this. Is like you can pass whatever in the accesControl if is a requester or proposer but, the caller is authorized for this request.

2024-10-24 16:25 UTC, ashitakah commented on solidity/test/integration/IntegrationBase.sol
> +    address[] memory _allowedCallers = new address[](1);
Also, the situations in which should revert if is not approved by access control are tested in the differents files.

2024-10-24 18:50 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    hasAccess(_request.accessControlModule, _CREATE_TYPEHASH, abi.encode(_request), _accessControl)
👍

2024-10-24 18:50 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +  mapping(address _user => mapping(address _accessControlModule => bool _approved)) public isAccessControlApproved;
👍

2024-10-24 18:50 UTC, ashitakah commented on solidity/contracts/Oracle.sol
>    function proposeResponse(
👍

2024-10-28 21:21 UTC, xorsal commented on solidity/contracts/Oracle.sol
> +    if (msg.sender != address(_currentRequest.disputeModule) && msg.sender != address(_currentRequest.resolutionModule))
nitpick: could we remove the redundant typecasting? `IOracle.Request.disputeModule` and `resolutionModule` are already of type `address`.

This is repeated several times in prophet-core and prophet-modules, maybe it makes sense to create a task to take care of it.

2024-10-28 21:23 UTC, xorsal commented on solidity/contracts/AccessController.sol
> +                data: _accessControl.data,
Would it make sense to encode the `IAccessController.AccessControl` object instead of passing user and bytes as separate values?

2024-10-31 22:34 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    if (msg.sender != address(_currentRequest.disputeModule) && msg.sender != address(_currentRequest.resolutionModule))
👍

2024-10-31 22:37 UTC, ashitakah commented on solidity/contracts/AccessController.sol
> +                data: _accessControl.data,
👍

2024-10-31 23:28 UTC, 0xJabberwock requested changes

2024-11-01 15:10 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    Dispute memory _dispute,
👍

2024-11-01 15:10 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    Dispute memory _dispute,
👍

2024-11-01 15:17 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    emit AccessControlModuleSet(msg.sender, _accessControlModule, _approved);
I think that the enumerable set makes no sense because is similar to the mapping logic, and we will need a view function to get the data. However, I like the idea to move the logic to the access controller.

2024-11-01 15:19 UTC, ashitakah commented on solidity/contracts/utils/OracleTypehash.sol
> +    keccak256('CreateRequest(Request _request,bytes32 _ipfsHash,AccessControl _accessControl');
Permit usage.

2024-11-01 15:20 UTC, ashitakah commented on solidity/interfaces/modules/accessControl/IAccessControlModule.sol
> +interface IAccessControlModule is IModule {
👍

2024-11-01 15:22 UTC, ashitakah commented on solidity/contracts/utils/OracleTypehash.sol
Zorzal will solve it in his PR

2024-11-01 15:26 UTC, ashitakah commented on solidity/interfaces/IAccessController.sol
> +    bytes data;
Basically is to avoid accessControlData.data

2024-11-04 05:29 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +    AccessControl calldata _accessControl
Because an access control module may want to require so.

2024-11-04 05:29 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +    AccessControl calldata _accessControl
Because an access control module may want to require so.

2024-11-04 05:47 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +    if (_accessControl.user != _response.proposer && _accessControl.user != address(_request.disputeModule)) {
Such dispute modules may set themselves as the access control users but not as the proposers; considering that that is the new expected behaviour:
- The user, not the caller, must be the proposer,
- unless the response is coming from a dispute module (i.e., `CircuitResolverModule` or `RootVerificationModule`).

2024-11-04 06:13 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +    emit AccessControlModuleSet(msg.sender, _accessControlModule, _approved);
Shouldn't the function check whether the setter had already approved the access control module, in order not to emit events when a state variable change didn't occur, or alternatively to revert?

2024-11-04 14:24 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    emit AccessControlModuleSet(msg.sender, _accessControlModule, _approved);
I can put a check or revert if the state its the same as before. I feel like its to much for a setter but I agree

2024-11-04 14:31 UTC, ashitakah commented on solidity/interfaces/IAccessController.sol
> +  error AccessControlData_NoAccess();
👍

2024-11-04 14:33 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    if (_accessControl.user != _response.proposer && _accessControl.user != address(_request.disputeModule)) {
👍

2024-11-04 14:37 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    if (_accessControl.user != _request.requester || _requestNonce != _request.nonce) {
IDEM above

2024-11-04 14:41 UTC, ashitakah commented on solidity/contracts/AccessController.sol
> +          && IAccessControlModule(_accessControlModule).hasAccess(
We discussed it, as we are calling an interface, we do not consider it necessary

2024-11-04 18:14 UTC, 0xJabberwock commented on solidity/contracts/utils/OracleTypehash.sol
> +  bytes32 public constant CREATE_TYPEHASH =
`OracleTypehash` need not be a contract, as [`Typehash`](https://github.com/defi-wonderland/prophet-modules/pull/74/files#diff-35a347edb83403574762ee51dfc4e6a53876c8987b12e5e2ef9afdf76ec75591R1-R22) isn't.

2024-11-04 18:28 UTC, 0xJabberwock commented on solidity/contracts/AccessController.sol
> +          && IAccessControlModule(_accessControlModule).hasAccess(
Hmm. I'm concerned about what an EOA fallback returns when called like that. Moreover, in any case, if the call reverts, `AccessController_NoAccess` wouldn't be thrown.

2024-11-05 03:10 UTC, ashitakah commented on solidity/contracts/utils/OracleTypehash.sol
> +  bytes32 public constant CREATE_TYPEHASH =
Yep but the problem that I found is when you try to release the npm package, our interface exporter makes a bad path if is not a contract. Thats why I change it

2024-11-05 03:24 UTC, ashitakah commented on solidity/contracts/utils/OracleTypehash.sol
> +}
👍

2024-11-05 03:32 UTC, ashitakah commented on solidity/contracts/AccessController.sol
> +          && IAccessControlModule(_accessControlModule).hasAccess(
Yep in that case you right, Im pretty sure that if you try to call a function in a EOA reverts, even so, for me its fine that revert with another data and nor use NoAccess because is not an access issue is about access control module is not a contract. However, if you want I can check that the destination address has bytecode, but for me is overcomplex and if we dont have it, should work in the same way

2024-11-05 11:45 UTC, gas1cent commented on solidity/contracts/AccessController.sol
> +          && IAccessControlModule(_accessControlModule).hasAccess(
@ashitakah agree with you on the difference between reverting with `NoAccess` and invalid call. We should add a test to cover the EOA case.

2024-11-05 15:53 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +    emit OracleRequestFinalized(_requestId, _responseId);
Considering that an `AccessControlModule is Module`, wouldn't it be proper to call `finalizeRequest()` there as well?

2024-11-06 18:56 UTC, ashitakah commented on solidity/contracts/Oracle.sol
> +    emit OracleRequestFinalized(_requestId, _responseId);
👍

2024-11-06 18:56 UTC, ashitakah commented on solidity/contracts/utils/OracleTypehash.sol
> +  bytes32 public constant CREATE_TYPEHASH =
👍

2024-11-06 18:56 UTC, ashitakah commented on solidity/contracts/AccessController.sol
> +          && IAccessControlModule(_accessControlModule).hasAccess(
👍

2024-11-07 05:13 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
>      _responseId = ValidatorLib._validateResponse(_request, _response);
Reminder: executing `isApproved` and `hasAccess` modifiers before any other validation might pose a security vulnerability, given that `Oracle` would perform an external call to an arbitrary address with arbitrary data from the user.

2024-11-07 05:39 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +    hasAccess(_request.accessControlModule, PROPOSE_TYPEHASH, abi.encode(_request, _response), _accessControl)
Taking into account the current design, the modules may call the `Oracle` setting themselves as the `AccessControl.user`—in consequence, they may have to pass through `isApproved` and `hasAccess`. Is this desirable?

2024-11-08 14:58 UTC, 0xJabberwock commented on solidity/contracts/OracleAccessController.sol
> +      revert OracleAccessController_AccessModuleNotApproved();
I vote for discarding `isApproved` and putting its logic within `hasAccess` modifier (as in `ModuleAccessController`).

Apart from that, both approval and access checks should only be performed when `msg.sender != _accessControl.user`, rather than when `_accessModule != address(0)`.

2024-11-08 15:06 UTC, 0xJabberwock commented on solidity/contracts/utils/OracleTypehash.sol
> +  bytes32 public constant CREATE_TYPEHASH =
Can it be a library?

2024-11-11 15:14 UTC, ashitakah commented on solidity/contracts/OracleAccessController.sol
> +      revert OracleAccessController_AccessModuleNotApproved();
👍

2024-11-11 18:07 UTC, gas1cent commented on solidity/contracts/Oracle.sol
> +
How come defining even more variables fixes the problem?

2024-11-11 18:13 UTC, xorsal commented on solidity/contracts/Oracle.sol
> +
I'll create a task to track this, but probably we shouldn't merge this PR without fixing it.

2024-11-11 18:36 UTC, gas1cent commented on solidity/interfaces/IOracleAccessController.sol
> +   * @notice Sets the approval of an the access module address.
```suggestion
   * @notice Sets the approval of an access module address.
```

2024-11-11 18:37 UTC, gas1cent commented on solidity/interfaces/modules/access/IAccessModule.sol
> +   * @param user The address of the user
```suggestion
```

2024-11-11 18:37 UTC, gas1cent commented on solidity/interfaces/modules/access/IAccessModule.sol
> +   * @param params The parameters for access control validation
```suggestion
   * @param typehashParams The parameters for access control validation
```

2024-11-11 18:52 UTC, 0xJabberwock commented on solidity/contracts/Oracle.sol
> +      IAccessModule(_request.accessModule).finalizeRequest(_request, _response, _accessControl.user);
`AccessModule::finalizeRequest` should be called once.

2024-11-12 07:11 UTC, gas1cent commented on solidity/contracts/Oracle.sol
> +      IAccessModule(_request.accessModule).finalizeRequest(_request, _response, _accessControl.user);
Fixed in https://github.com/defi-wonderland/prophet-core/pull/52/commits/ba7cf26e30831fd9e250256c44cfb9f277508aaa

2024-11-12 07:11 UTC, gas1cent commented on solidity/interfaces/modules/access/IAccessModule.sol
> +   * @param params The parameters for access control validation
https://github.com/defi-wonderland/prophet-core/pull/52/commits/1d1e5a38da02c1d704a773bdb147dd31f3010f6b

2024-11-12 07:11 UTC, gas1cent commented on solidity/interfaces/modules/access/IAccessModule.sol
> +   * @param user The address of the user
https://github.com/defi-wonderland/prophet-core/pull/52/commits/1d1e5a38da02c1d704a773bdb147dd31f3010f6b

2024-11-12 07:11 UTC, gas1cent commented on solidity/interfaces/IOracleAccessController.sol
> +   * @notice Sets the approval of an the access module address.
https://github.com/defi-wonderland/prophet-core/pull/52/commits/1d1e5a38da02c1d704a773bdb147dd31f3010f6b

2024-11-12 07:11 UTC, gas1cent commented on solidity/contracts/Oracle.sol
> +
Fixed in https://github.com/defi-wonderland/prophet-core/pull/52/commits/d34d4baf68d32ef1bd70210f55dfde8d9a0f37ea

2024-11-12 09:44 UTC, xorsal approved these changes

2024-11-12 12:40 UTC, xorsal commented on solidity/test/unit/Oracle.t.sol
> +  event OracleRequestFinalized(bytes32 indexed _requestId, bytes32 indexed _responseId);
Very nice! Tracked in OPT-536

2024-11-12 14:14 UTC, 0xJabberwock approved these changes
🚀

2024-11-12 14:21 UTC, merged